// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package zoopla

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Pricing_TransactionType int32

const (
	Pricing_rent Pricing_TransactionType = 0
	Pricing_sale Pricing_TransactionType = 1
)

var Pricing_TransactionType_name = map[int32]string{
	0: "rent",
	1: "sale",
}

var Pricing_TransactionType_value = map[string]int32{
	"rent": 0,
	"sale": 1,
}

func (x Pricing_TransactionType) String() string {
	return proto.EnumName(Pricing_TransactionType_name, int32(x))
}

func (Pricing_TransactionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5, 0}
}

type Pricing_RentFrequency int32

const (
	Pricing_per_person_per_week Pricing_RentFrequency = 0
	Pricing_per_week            Pricing_RentFrequency = 1
	Pricing_per_month           Pricing_RentFrequency = 2
	Pricing_per_quarter         Pricing_RentFrequency = 3
	Pricing_per_year            Pricing_RentFrequency = 4
)

var Pricing_RentFrequency_name = map[int32]string{
	0: "per_person_per_week",
	1: "per_week",
	2: "per_month",
	3: "per_quarter",
	4: "per_year",
}

var Pricing_RentFrequency_value = map[string]int32{
	"per_person_per_week": 0,
	"per_week":            1,
	"per_month":           2,
	"per_quarter":         3,
	"per_year":            4,
}

func (x Pricing_RentFrequency) String() string {
	return proto.EnumName(Pricing_RentFrequency_name, int32(x))
}

func (Pricing_RentFrequency) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5, 1}
}

type Coordinates struct {
	Latitude             float64  `protobuf:"fixed64,1,opt,name=Latitude,proto3" json:"Latitude,omitempty"`
	Longitude            float64  `protobuf:"fixed64,2,opt,name=Longitude,proto3" json:"Longitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Coordinates) Reset()         { *m = Coordinates{} }
func (m *Coordinates) String() string { return proto.CompactTextString(m) }
func (*Coordinates) ProtoMessage()    {}
func (*Coordinates) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *Coordinates) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Coordinates.Unmarshal(m, b)
}
func (m *Coordinates) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Coordinates.Marshal(b, m, deterministic)
}
func (m *Coordinates) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Coordinates.Merge(m, src)
}
func (m *Coordinates) XXX_Size() int {
	return xxx_messageInfo_Coordinates.Size(m)
}
func (m *Coordinates) XXX_DiscardUnknown() {
	xxx_messageInfo_Coordinates.DiscardUnknown(m)
}

var xxx_messageInfo_Coordinates proto.InternalMessageInfo

func (m *Coordinates) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Coordinates) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

type PafAddress struct {
	AddressKey           string   `protobuf:"bytes,1,opt,name=AddressKey,proto3" json:"AddressKey,omitempty"`
	OrganisationKey      string   `protobuf:"bytes,2,opt,name=OrganisationKey,proto3" json:"OrganisationKey,omitempty"`
	PostcodeType         string   `protobuf:"bytes,3,opt,name=PostcodeType,proto3" json:"PostcodeType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PafAddress) Reset()         { *m = PafAddress{} }
func (m *PafAddress) String() string { return proto.CompactTextString(m) }
func (*PafAddress) ProtoMessage()    {}
func (*PafAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *PafAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PafAddress.Unmarshal(m, b)
}
func (m *PafAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PafAddress.Marshal(b, m, deterministic)
}
func (m *PafAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PafAddress.Merge(m, src)
}
func (m *PafAddress) XXX_Size() int {
	return xxx_messageInfo_PafAddress.Size(m)
}
func (m *PafAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_PafAddress.DiscardUnknown(m)
}

var xxx_messageInfo_PafAddress proto.InternalMessageInfo

func (m *PafAddress) GetAddressKey() string {
	if m != nil {
		return m.AddressKey
	}
	return ""
}

func (m *PafAddress) GetOrganisationKey() string {
	if m != nil {
		return m.OrganisationKey
	}
	return ""
}

func (m *PafAddress) GetPostcodeType() string {
	if m != nil {
		return m.PostcodeType
	}
	return ""
}

type Location struct {
	CountryCode          string       `protobuf:"bytes,1,opt,name=CountryCode,proto3" json:"CountryCode,omitempty"`
	PostalCode           string       `protobuf:"bytes,2,opt,name=PostalCode,proto3" json:"PostalCode,omitempty"`
	PropertyNumberOrName string       `protobuf:"bytes,3,opt,name=PropertyNumberOrName,proto3" json:"PropertyNumberOrName,omitempty"`
	StreetName           string       `protobuf:"bytes,4,opt,name=StreetName,proto3" json:"StreetName,omitempty"`
	TownOrCity           string       `protobuf:"bytes,5,opt,name=TownOrCity,proto3" json:"TownOrCity,omitempty"`
	Coordinates          *Coordinates `protobuf:"bytes,6,opt,name=Coordinates,proto3" json:"Coordinates,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (m *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(m, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetCountryCode() string {
	if m != nil {
		return m.CountryCode
	}
	return ""
}

func (m *Location) GetPostalCode() string {
	if m != nil {
		return m.PostalCode
	}
	return ""
}

func (m *Location) GetPropertyNumberOrName() string {
	if m != nil {
		return m.PropertyNumberOrName
	}
	return ""
}

func (m *Location) GetStreetName() string {
	if m != nil {
		return m.StreetName
	}
	return ""
}

func (m *Location) GetTownOrCity() string {
	if m != nil {
		return m.TownOrCity
	}
	return ""
}

func (m *Location) GetCoordinates() *Coordinates {
	if m != nil {
		return m.Coordinates
	}
	return nil
}

type DetailedDescription struct {
	Dimensions           string   `protobuf:"bytes,1,opt,name=Dimensions,proto3" json:"Dimensions,omitempty"`
	Heading              string   `protobuf:"bytes,2,opt,name=Heading,proto3" json:"Heading,omitempty"`
	Text                 string   `protobuf:"bytes,3,opt,name=Text,proto3" json:"Text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DetailedDescription) Reset()         { *m = DetailedDescription{} }
func (m *DetailedDescription) String() string { return proto.CompactTextString(m) }
func (*DetailedDescription) ProtoMessage()    {}
func (*DetailedDescription) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *DetailedDescription) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetailedDescription.Unmarshal(m, b)
}
func (m *DetailedDescription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetailedDescription.Marshal(b, m, deterministic)
}
func (m *DetailedDescription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetailedDescription.Merge(m, src)
}
func (m *DetailedDescription) XXX_Size() int {
	return xxx_messageInfo_DetailedDescription.Size(m)
}
func (m *DetailedDescription) XXX_DiscardUnknown() {
	xxx_messageInfo_DetailedDescription.DiscardUnknown(m)
}

var xxx_messageInfo_DetailedDescription proto.InternalMessageInfo

func (m *DetailedDescription) GetDimensions() string {
	if m != nil {
		return m.Dimensions
	}
	return ""
}

func (m *DetailedDescription) GetHeading() string {
	if m != nil {
		return m.Heading
	}
	return ""
}

func (m *DetailedDescription) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type PricePerUnitArea struct {
	Price                float64  `protobuf:"fixed64,1,opt,name=Price,proto3" json:"Price,omitempty"`
	Units                string   `protobuf:"bytes,2,opt,name=Units,proto3" json:"Units,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PricePerUnitArea) Reset()         { *m = PricePerUnitArea{} }
func (m *PricePerUnitArea) String() string { return proto.CompactTextString(m) }
func (*PricePerUnitArea) ProtoMessage()    {}
func (*PricePerUnitArea) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *PricePerUnitArea) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PricePerUnitArea.Unmarshal(m, b)
}
func (m *PricePerUnitArea) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PricePerUnitArea.Marshal(b, m, deterministic)
}
func (m *PricePerUnitArea) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PricePerUnitArea.Merge(m, src)
}
func (m *PricePerUnitArea) XXX_Size() int {
	return xxx_messageInfo_PricePerUnitArea.Size(m)
}
func (m *PricePerUnitArea) XXX_DiscardUnknown() {
	xxx_messageInfo_PricePerUnitArea.DiscardUnknown(m)
}

var xxx_messageInfo_PricePerUnitArea proto.InternalMessageInfo

func (m *PricePerUnitArea) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *PricePerUnitArea) GetUnits() string {
	if m != nil {
		return m.Units
	}
	return ""
}

type Pricing struct {
	TransactionType      Pricing_TransactionType `protobuf:"varint,1,opt,name=transactionType,proto3,enum=mashroom.zoopla.Pricing_TransactionType" json:"transactionType,omitempty"`
	CurrencyCode         string                  `protobuf:"bytes,2,opt,name=CurrencyCode,proto3" json:"CurrencyCode,omitempty"`
	Price                float64                 `protobuf:"fixed64,3,opt,name=Price,proto3" json:"Price,omitempty"`
	RentFrequency        Pricing_RentFrequency   `protobuf:"varint,4,opt,name=rentFrequency,proto3,enum=mashroom.zoopla.Pricing_RentFrequency" json:"rentFrequency,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *Pricing) Reset()         { *m = Pricing{} }
func (m *Pricing) String() string { return proto.CompactTextString(m) }
func (*Pricing) ProtoMessage()    {}
func (*Pricing) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}

func (m *Pricing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pricing.Unmarshal(m, b)
}
func (m *Pricing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pricing.Marshal(b, m, deterministic)
}
func (m *Pricing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pricing.Merge(m, src)
}
func (m *Pricing) XXX_Size() int {
	return xxx_messageInfo_Pricing.Size(m)
}
func (m *Pricing) XXX_DiscardUnknown() {
	xxx_messageInfo_Pricing.DiscardUnknown(m)
}

var xxx_messageInfo_Pricing proto.InternalMessageInfo

func (m *Pricing) GetTransactionType() Pricing_TransactionType {
	if m != nil {
		return m.TransactionType
	}
	return Pricing_rent
}

func (m *Pricing) GetCurrencyCode() string {
	if m != nil {
		return m.CurrencyCode
	}
	return ""
}

func (m *Pricing) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Pricing) GetRentFrequency() Pricing_RentFrequency {
	if m != nil {
		return m.RentFrequency
	}
	return Pricing_per_person_per_week
}

type BranchUpdateRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BranchUpdateRequest) Reset()         { *m = BranchUpdateRequest{} }
func (m *BranchUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*BranchUpdateRequest) ProtoMessage()    {}
func (*BranchUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{6}
}

func (m *BranchUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BranchUpdateRequest.Unmarshal(m, b)
}
func (m *BranchUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BranchUpdateRequest.Marshal(b, m, deterministic)
}
func (m *BranchUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BranchUpdateRequest.Merge(m, src)
}
func (m *BranchUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_BranchUpdateRequest.Size(m)
}
func (m *BranchUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BranchUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BranchUpdateRequest proto.InternalMessageInfo

type BranchUpdateResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	BranchReference      string   `protobuf:"bytes,2,opt,name=branchReference,proto3" json:"branchReference,omitempty"`
	NewBranch            bool     `protobuf:"varint,3,opt,name=newBranch,proto3" json:"newBranch,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BranchUpdateResponse) Reset()         { *m = BranchUpdateResponse{} }
func (m *BranchUpdateResponse) String() string { return proto.CompactTextString(m) }
func (*BranchUpdateResponse) ProtoMessage()    {}
func (*BranchUpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{7}
}

func (m *BranchUpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BranchUpdateResponse.Unmarshal(m, b)
}
func (m *BranchUpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BranchUpdateResponse.Marshal(b, m, deterministic)
}
func (m *BranchUpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BranchUpdateResponse.Merge(m, src)
}
func (m *BranchUpdateResponse) XXX_Size() int {
	return xxx_messageInfo_BranchUpdateResponse.Size(m)
}
func (m *BranchUpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BranchUpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BranchUpdateResponse proto.InternalMessageInfo

func (m *BranchUpdateResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *BranchUpdateResponse) GetBranchReference() string {
	if m != nil {
		return m.BranchReference
	}
	return ""
}

func (m *BranchUpdateResponse) GetNewBranch() bool {
	if m != nil {
		return m.NewBranch
	}
	return false
}

type ListingUpdateRequest struct {
	BranchReference      string                 `protobuf:"bytes,1,opt,name=BranchReference,proto3" json:"BranchReference,omitempty"`
	Category             string                 `protobuf:"bytes,2,opt,name=Category,proto3" json:"Category,omitempty"`
	DetailedDescription  []*DetailedDescription `protobuf:"bytes,3,rep,name=DetailedDescription,proto3" json:"DetailedDescription,omitempty"`
	LifeCycleStatus      string                 `protobuf:"bytes,4,opt,name=LifeCycleStatus,proto3" json:"LifeCycleStatus,omitempty"`
	ListingReference     string                 `protobuf:"bytes,5,opt,name=ListingReference,proto3" json:"ListingReference,omitempty"`
	Location             *Location              `protobuf:"bytes,6,opt,name=Location,proto3" json:"Location,omitempty"`
	Pricing              *Pricing               `protobuf:"bytes,7,opt,name=Pricing,proto3" json:"Pricing,omitempty"`
	PropertyType         string                 `protobuf:"bytes,8,opt,name=PropertyType,proto3" json:"PropertyType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ListingUpdateRequest) Reset()         { *m = ListingUpdateRequest{} }
func (m *ListingUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*ListingUpdateRequest) ProtoMessage()    {}
func (*ListingUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{8}
}

func (m *ListingUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListingUpdateRequest.Unmarshal(m, b)
}
func (m *ListingUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListingUpdateRequest.Marshal(b, m, deterministic)
}
func (m *ListingUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListingUpdateRequest.Merge(m, src)
}
func (m *ListingUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_ListingUpdateRequest.Size(m)
}
func (m *ListingUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListingUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListingUpdateRequest proto.InternalMessageInfo

func (m *ListingUpdateRequest) GetBranchReference() string {
	if m != nil {
		return m.BranchReference
	}
	return ""
}

func (m *ListingUpdateRequest) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *ListingUpdateRequest) GetDetailedDescription() []*DetailedDescription {
	if m != nil {
		return m.DetailedDescription
	}
	return nil
}

func (m *ListingUpdateRequest) GetLifeCycleStatus() string {
	if m != nil {
		return m.LifeCycleStatus
	}
	return ""
}

func (m *ListingUpdateRequest) GetListingReference() string {
	if m != nil {
		return m.ListingReference
	}
	return ""
}

func (m *ListingUpdateRequest) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *ListingUpdateRequest) GetPricing() *Pricing {
	if m != nil {
		return m.Pricing
	}
	return nil
}

func (m *ListingUpdateRequest) GetPropertyType() string {
	if m != nil {
		return m.PropertyType
	}
	return ""
}

type ListingUpdateResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ListingReference     string   `protobuf:"bytes,2,opt,name=listingReference,proto3" json:"listingReference,omitempty"`
	Etag                 string   `protobuf:"bytes,3,opt,name=etag,proto3" json:"etag,omitempty"`
	Url                  string   `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	NewListing           bool     `protobuf:"varint,5,opt,name=newListing,proto3" json:"newListing,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListingUpdateResponse) Reset()         { *m = ListingUpdateResponse{} }
func (m *ListingUpdateResponse) String() string { return proto.CompactTextString(m) }
func (*ListingUpdateResponse) ProtoMessage()    {}
func (*ListingUpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{9}
}

func (m *ListingUpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListingUpdateResponse.Unmarshal(m, b)
}
func (m *ListingUpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListingUpdateResponse.Marshal(b, m, deterministic)
}
func (m *ListingUpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListingUpdateResponse.Merge(m, src)
}
func (m *ListingUpdateResponse) XXX_Size() int {
	return xxx_messageInfo_ListingUpdateResponse.Size(m)
}
func (m *ListingUpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListingUpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListingUpdateResponse proto.InternalMessageInfo

func (m *ListingUpdateResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *ListingUpdateResponse) GetListingReference() string {
	if m != nil {
		return m.ListingReference
	}
	return ""
}

func (m *ListingUpdateResponse) GetEtag() string {
	if m != nil {
		return m.Etag
	}
	return ""
}

func (m *ListingUpdateResponse) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *ListingUpdateResponse) GetNewListing() bool {
	if m != nil {
		return m.NewListing
	}
	return false
}

type ListingDeleteRequest struct {
	ListingReference     string   `protobuf:"bytes,1,opt,name=listingReference,proto3" json:"listingReference,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListingDeleteRequest) Reset()         { *m = ListingDeleteRequest{} }
func (m *ListingDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*ListingDeleteRequest) ProtoMessage()    {}
func (*ListingDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{10}
}

func (m *ListingDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListingDeleteRequest.Unmarshal(m, b)
}
func (m *ListingDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListingDeleteRequest.Marshal(b, m, deterministic)
}
func (m *ListingDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListingDeleteRequest.Merge(m, src)
}
func (m *ListingDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_ListingDeleteRequest.Size(m)
}
func (m *ListingDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListingDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListingDeleteRequest proto.InternalMessageInfo

func (m *ListingDeleteRequest) GetListingReference() string {
	if m != nil {
		return m.ListingReference
	}
	return ""
}

type ListingDeleteResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ListingReference     string   `protobuf:"bytes,2,opt,name=listingReference,proto3" json:"listingReference,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListingDeleteResponse) Reset()         { *m = ListingDeleteResponse{} }
func (m *ListingDeleteResponse) String() string { return proto.CompactTextString(m) }
func (*ListingDeleteResponse) ProtoMessage()    {}
func (*ListingDeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{11}
}

func (m *ListingDeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListingDeleteResponse.Unmarshal(m, b)
}
func (m *ListingDeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListingDeleteResponse.Marshal(b, m, deterministic)
}
func (m *ListingDeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListingDeleteResponse.Merge(m, src)
}
func (m *ListingDeleteResponse) XXX_Size() int {
	return xxx_messageInfo_ListingDeleteResponse.Size(m)
}
func (m *ListingDeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListingDeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListingDeleteResponse proto.InternalMessageInfo

func (m *ListingDeleteResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *ListingDeleteResponse) GetListingReference() string {
	if m != nil {
		return m.ListingReference
	}
	return ""
}

type ListingListRequest struct {
	BranchReference      string   `protobuf:"bytes,1,opt,name=branchReference,proto3" json:"branchReference,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListingListRequest) Reset()         { *m = ListingListRequest{} }
func (m *ListingListRequest) String() string { return proto.CompactTextString(m) }
func (*ListingListRequest) ProtoMessage()    {}
func (*ListingListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{12}
}

func (m *ListingListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListingListRequest.Unmarshal(m, b)
}
func (m *ListingListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListingListRequest.Marshal(b, m, deterministic)
}
func (m *ListingListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListingListRequest.Merge(m, src)
}
func (m *ListingListRequest) XXX_Size() int {
	return xxx_messageInfo_ListingListRequest.Size(m)
}
func (m *ListingListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListingListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListingListRequest proto.InternalMessageInfo

func (m *ListingListRequest) GetBranchReference() string {
	if m != nil {
		return m.BranchReference
	}
	return ""
}

type Listing struct {
	ListingReference     string   `protobuf:"bytes,1,opt,name=ListingReference,proto3" json:"ListingReference,omitempty"`
	ListingEtag          string   `protobuf:"bytes,2,opt,name=ListingEtag,proto3" json:"ListingEtag,omitempty"`
	URL                  string   `protobuf:"bytes,3,opt,name=URL,proto3" json:"URL,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Listing) Reset()         { *m = Listing{} }
func (m *Listing) String() string { return proto.CompactTextString(m) }
func (*Listing) ProtoMessage()    {}
func (*Listing) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{13}
}

func (m *Listing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Listing.Unmarshal(m, b)
}
func (m *Listing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Listing.Marshal(b, m, deterministic)
}
func (m *Listing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Listing.Merge(m, src)
}
func (m *Listing) XXX_Size() int {
	return xxx_messageInfo_Listing.Size(m)
}
func (m *Listing) XXX_DiscardUnknown() {
	xxx_messageInfo_Listing.DiscardUnknown(m)
}

var xxx_messageInfo_Listing proto.InternalMessageInfo

func (m *Listing) GetListingReference() string {
	if m != nil {
		return m.ListingReference
	}
	return ""
}

func (m *Listing) GetListingEtag() string {
	if m != nil {
		return m.ListingEtag
	}
	return ""
}

func (m *Listing) GetURL() string {
	if m != nil {
		return m.URL
	}
	return ""
}

type ListingListResponse struct {
	Status               string     `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	BranchReference      string     `protobuf:"bytes,2,opt,name=branchReference,proto3" json:"branchReference,omitempty"`
	Listings             []*Listing `protobuf:"bytes,3,rep,name=listings,proto3" json:"listings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListingListResponse) Reset()         { *m = ListingListResponse{} }
func (m *ListingListResponse) String() string { return proto.CompactTextString(m) }
func (*ListingListResponse) ProtoMessage()    {}
func (*ListingListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{14}
}

func (m *ListingListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListingListResponse.Unmarshal(m, b)
}
func (m *ListingListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListingListResponse.Marshal(b, m, deterministic)
}
func (m *ListingListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListingListResponse.Merge(m, src)
}
func (m *ListingListResponse) XXX_Size() int {
	return xxx_messageInfo_ListingListResponse.Size(m)
}
func (m *ListingListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListingListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListingListResponse proto.InternalMessageInfo

func (m *ListingListResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *ListingListResponse) GetBranchReference() string {
	if m != nil {
		return m.BranchReference
	}
	return ""
}

func (m *ListingListResponse) GetListings() []*Listing {
	if m != nil {
		return m.Listings
	}
	return nil
}

func init() {
	proto.RegisterEnum("mashroom.zoopla.Pricing_TransactionType", Pricing_TransactionType_name, Pricing_TransactionType_value)
	proto.RegisterEnum("mashroom.zoopla.Pricing_RentFrequency", Pricing_RentFrequency_name, Pricing_RentFrequency_value)
	proto.RegisterType((*Coordinates)(nil), "mashroom.zoopla.Coordinates")
	proto.RegisterType((*PafAddress)(nil), "mashroom.zoopla.PafAddress")
	proto.RegisterType((*Location)(nil), "mashroom.zoopla.Location")
	proto.RegisterType((*DetailedDescription)(nil), "mashroom.zoopla.DetailedDescription")
	proto.RegisterType((*PricePerUnitArea)(nil), "mashroom.zoopla.PricePerUnitArea")
	proto.RegisterType((*Pricing)(nil), "mashroom.zoopla.Pricing")
	proto.RegisterType((*BranchUpdateRequest)(nil), "mashroom.zoopla.BranchUpdateRequest")
	proto.RegisterType((*BranchUpdateResponse)(nil), "mashroom.zoopla.BranchUpdateResponse")
	proto.RegisterType((*ListingUpdateRequest)(nil), "mashroom.zoopla.ListingUpdateRequest")
	proto.RegisterType((*ListingUpdateResponse)(nil), "mashroom.zoopla.ListingUpdateResponse")
	proto.RegisterType((*ListingDeleteRequest)(nil), "mashroom.zoopla.ListingDeleteRequest")
	proto.RegisterType((*ListingDeleteResponse)(nil), "mashroom.zoopla.ListingDeleteResponse")
	proto.RegisterType((*ListingListRequest)(nil), "mashroom.zoopla.ListingListRequest")
	proto.RegisterType((*Listing)(nil), "mashroom.zoopla.Listing")
	proto.RegisterType((*ListingListResponse)(nil), "mashroom.zoopla.ListingListResponse")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 970 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0x4d, 0x6f, 0xdb, 0x46,
	0x13, 0x0e, 0x2d, 0xc7, 0x96, 0x46, 0xb6, 0x45, 0xac, 0x9d, 0xf7, 0x55, 0x8d, 0x20, 0x10, 0xd8,
	0x38, 0x10, 0x02, 0x54, 0x46, 0x95, 0xf6, 0x6a, 0x20, 0x96, 0xfb, 0x01, 0x54, 0x88, 0x05, 0x5a,
	0xee, 0x21, 0x39, 0x18, 0x2b, 0x72, 0x2c, 0x13, 0xa6, 0x76, 0x99, 0xdd, 0x55, 0x5c, 0xe5, 0xd4,
	0x43, 0xaf, 0xfd, 0x01, 0x3d, 0xf6, 0x2f, 0xf6, 0x17, 0x14, 0xbb, 0x5c, 0x8a, 0x1f, 0x92, 0xea,
	0x4b, 0x4e, 0xe2, 0x3c, 0xfb, 0xec, 0xec, 0x7c, 0x3c, 0x33, 0x10, 0x34, 0x68, 0x12, 0xf5, 0x12,
	0xc1, 0x15, 0x27, 0xad, 0x19, 0x95, 0x77, 0x82, 0xf3, 0x59, 0xef, 0x33, 0xe7, 0x49, 0x4c, 0xbd,
	0x9f, 0xa0, 0x39, 0xe0, 0x5c, 0x84, 0x11, 0xa3, 0x0a, 0x25, 0x39, 0x86, 0xfa, 0x90, 0xaa, 0x48,
	0xcd, 0x43, 0x6c, 0x3b, 0x1d, 0xa7, 0xeb, 0xf8, 0x4b, 0x9b, 0x3c, 0x87, 0xc6, 0x90, 0xb3, 0x69,
	0x7a, 0xb8, 0x65, 0x0e, 0x73, 0xc0, 0xfb, 0x0c, 0x30, 0xa2, 0xb7, 0x6f, 0xc3, 0x50, 0xa0, 0x94,
	0xe4, 0x05, 0x80, 0xfd, 0xfc, 0x05, 0x17, 0xc6, 0x53, 0xc3, 0x2f, 0x20, 0xa4, 0x0b, 0xad, 0x4b,
	0x31, 0xa5, 0x2c, 0x92, 0x54, 0x45, 0x9c, 0x69, 0xd2, 0x96, 0x21, 0x55, 0x61, 0xe2, 0xc1, 0xde,
	0x88, 0x4b, 0x15, 0xf0, 0x10, 0xc7, 0x8b, 0x04, 0xdb, 0x35, 0x43, 0x2b, 0x61, 0xde, 0xef, 0x5b,
	0x50, 0x1f, 0xf2, 0xc0, 0xdc, 0x21, 0x1d, 0x9d, 0xd1, 0x9c, 0x29, 0xb1, 0x18, 0x70, 0x9b, 0x45,
	0xc3, 0x2f, 0x42, 0x3a, 0x38, 0x7d, 0x9d, 0xc6, 0x86, 0x90, 0xbe, 0x5b, 0x40, 0x48, 0x1f, 0x8e,
	0x46, 0x82, 0x27, 0x28, 0xd4, 0xe2, 0xdd, 0x7c, 0x36, 0x41, 0x71, 0x29, 0xde, 0xd1, 0x59, 0xf6,
	0xf4, 0xda, 0x33, 0xed, 0xf3, 0x4a, 0x09, 0x44, 0x65, 0x98, 0xdb, 0xa9, 0xcf, 0x1c, 0xd1, 0xe7,
	0x63, 0xfe, 0xc0, 0x2e, 0xc5, 0x20, 0x52, 0x8b, 0xf6, 0xd3, 0xf4, 0x3c, 0x47, 0xc8, 0x59, 0xa9,
	0x0f, 0xed, 0x9d, 0x8e, 0xd3, 0x6d, 0xf6, 0x9f, 0xf7, 0x2a, 0xed, 0xea, 0x15, 0x38, 0x7e, 0xf1,
	0x82, 0x17, 0xc0, 0xe1, 0x05, 0x2a, 0x1a, 0xc5, 0x18, 0x5e, 0xa0, 0x0c, 0x44, 0x94, 0x98, 0x62,
	0xbc, 0x00, 0xb8, 0x88, 0x66, 0xc8, 0x64, 0xc4, 0x99, 0xcc, 0xfa, 0x90, 0x23, 0xa4, 0x0d, 0xbb,
	0x3f, 0x23, 0x0d, 0x23, 0x36, 0xb5, 0x75, 0xc8, 0x4c, 0x42, 0x60, 0x7b, 0x8c, 0xbf, 0x29, 0x9b,
	0xb4, 0xf9, 0xf6, 0xce, 0xc0, 0x1d, 0x89, 0x28, 0xc0, 0x11, 0x8a, 0x6b, 0x16, 0xa9, 0xb7, 0x02,
	0x29, 0x39, 0x82, 0xa7, 0x06, 0xb3, 0x72, 0x49, 0x0d, 0x8d, 0x6a, 0x86, 0xb4, 0x5e, 0x53, 0xc3,
	0xfb, 0x67, 0x0b, 0x76, 0xf5, 0xb9, 0xf6, 0xef, 0x43, 0x4b, 0x09, 0xca, 0x24, 0x0d, 0x74, 0xa0,
	0xa6, 0xb5, 0xda, 0xc3, 0x41, 0xbf, 0xbb, 0x92, 0xb4, 0xbd, 0xd2, 0x1b, 0x97, 0xf9, 0x7e, 0xd5,
	0x81, 0xd6, 0xca, 0x60, 0x2e, 0x04, 0xb2, 0x60, 0x51, 0x68, 0x6d, 0x09, 0xcb, 0xe3, 0xad, 0x15,
	0xe3, 0x1d, 0xc2, 0xbe, 0x40, 0xa6, 0x7e, 0x14, 0xf8, 0x71, 0xae, 0xa9, 0xa6, 0x83, 0x07, 0xfd,
	0x57, 0x1b, 0x63, 0xf1, 0x8b, 0x6c, 0xbf, 0x7c, 0xd9, 0x3b, 0x81, 0x56, 0x25, 0x56, 0x52, 0x87,
	0x6d, 0xcd, 0x71, 0x9f, 0xe8, 0x2f, 0x49, 0x63, 0x74, 0x1d, 0x2f, 0x84, 0xfd, 0x92, 0x1b, 0xf2,
	0x7f, 0x38, 0x4c, 0x50, 0xdc, 0x24, 0x28, 0x24, 0x67, 0xfa, 0xe7, 0xe6, 0x01, 0xf1, 0xde, 0x7d,
	0x42, 0xf6, 0xa0, 0xbe, 0xb4, 0x1c, 0xb2, 0x0f, 0x0d, 0x6d, 0xcd, 0x38, 0x53, 0x77, 0xee, 0x16,
	0x69, 0x41, 0x53, 0x9b, 0x1f, 0xe7, 0x54, 0x28, 0x14, 0x6e, 0x2d, 0x63, 0x2f, 0x90, 0x0a, 0x77,
	0xdb, 0x7b, 0x06, 0x87, 0xe7, 0x82, 0xb2, 0xe0, 0xee, 0x3a, 0x09, 0xa9, 0x42, 0x5f, 0x3f, 0x26,
	0x95, 0xf7, 0x09, 0x8e, 0xca, 0xb0, 0x4c, 0x38, 0x93, 0x48, 0xfe, 0x07, 0x3b, 0x52, 0x51, 0x35,
	0xcf, 0xd4, 0x62, 0x2d, 0x3d, 0xb1, 0x13, 0xc3, 0xf7, 0xf1, 0x16, 0x75, 0x39, 0xb3, 0xf2, 0x56,
	0x61, 0xbd, 0x27, 0x18, 0x3e, 0xa4, 0xce, 0x4d, 0x95, 0xeb, 0x7e, 0x0e, 0x78, 0x7f, 0xd5, 0xe0,
	0x68, 0x18, 0x49, 0x15, 0xb1, 0x69, 0x29, 0x20, 0xfd, 0xc0, 0x79, 0xe5, 0x81, 0x34, 0x82, 0x2a,
	0xac, 0x97, 0xd4, 0x80, 0x2a, 0x9c, 0x72, 0x91, 0x6d, 0x8d, 0xa5, 0x4d, 0x7e, 0x5d, 0x3b, 0x07,
	0xed, 0x5a, 0xa7, 0xd6, 0x6d, 0xf6, 0x5f, 0xae, 0xb4, 0x73, 0x0d, 0xd7, 0x5f, 0x3b, 0x48, 0x5d,
	0x68, 0x0d, 0xa3, 0x5b, 0x1c, 0x2c, 0x82, 0x18, 0xaf, 0xd2, 0xfa, 0xa4, 0x43, 0x5e, 0x85, 0xc9,
	0x6b, 0x70, 0x6d, 0x7e, 0x79, 0x22, 0xe9, 0xbc, 0xaf, 0xe0, 0xe4, 0xfb, 0x7c, 0x6f, 0xd9, 0x91,
	0xff, 0x6a, 0x25, 0xc4, 0x8c, 0xe0, 0xe7, 0x2b, 0xae, 0xbf, 0x1c, 0xa3, 0xf6, 0xae, 0xb9, 0xd5,
	0xde, 0xa4, 0x53, 0x7f, 0x39, 0x6f, 0x7a, 0x8f, 0xda, 0xc5, 0x65, 0x86, 0xad, 0x6e, 0xf7, 0x68,
	0x01, 0xf3, 0xfe, 0x76, 0xe0, 0x59, 0xa5, 0x37, 0x8f, 0xa8, 0xe2, 0x35, 0xb8, 0x71, 0x35, 0xd9,
	0xb4, 0x25, 0x2b, 0xb8, 0xde, 0x28, 0xa8, 0xe8, 0x34, 0xdb, 0x28, 0xfa, 0x9b, 0xb8, 0x50, 0x9b,
	0x8b, 0xd8, 0x96, 0x52, 0x7f, 0xea, 0x8d, 0xc5, 0xf0, 0xc1, 0x46, 0x61, 0x0a, 0x57, 0xf7, 0x0b,
	0x88, 0x77, 0xbe, 0x94, 0xcf, 0x05, 0xc6, 0x98, 0xcb, 0x67, 0x5d, 0x24, 0xce, 0xfa, 0x48, 0xbc,
	0x0f, 0xcb, 0x34, 0x33, 0x1f, 0x5f, 0x2e, 0x4d, 0xef, 0x0c, 0x88, 0x75, 0xae, 0x7f, 0x0a, 0xea,
	0x9e, 0xac, 0x57, 0x77, 0x05, 0xf6, 0x22, 0xd8, 0xb5, 0xf7, 0xd7, 0x4a, 0xc9, 0xd9, 0x20, 0xa5,
	0x0e, 0x34, 0x2d, 0xf6, 0x83, 0x2e, 0x72, 0x1a, 0x5d, 0x11, 0xd2, 0xb5, 0xbe, 0xf6, 0x87, 0xb6,
	0xfc, 0xfa, 0xd3, 0xfb, 0xd3, 0x81, 0xc3, 0x52, 0xac, 0x5f, 0x6c, 0x07, 0x7c, 0x07, 0x75, 0x5b,
	0x18, 0x69, 0x67, 0x6f, 0x55, 0xa2, 0x59, 0x0a, 0x4b, 0x66, 0xff, 0x8f, 0x1a, 0xec, 0xbf, 0x37,
	0x87, 0x57, 0x28, 0x3e, 0xe9, 0xbd, 0xfc, 0x01, 0xf6, 0x8a, 0x5b, 0x8a, 0xac, 0x4e, 0xf0, 0x9a,
	0xdd, 0x76, 0x7c, 0xf2, 0x08, 0xcb, 0xa6, 0x79, 0x03, 0x07, 0x29, 0x92, 0x0d, 0x01, 0x39, 0xd9,
	0x14, 0x64, 0xd9, 0xff, 0xab, 0xc7, 0x68, 0xf9, 0x03, 0xa9, 0xc0, 0x1e, 0x7f, 0xa0, 0x24, 0xe6,
	0xcd, 0x0f, 0x54, 0xf4, 0x3a, 0xce, 0xb5, 0xf2, 0xf5, 0xa6, 0x2b, 0x05, 0x15, 0x1e, 0xbf, 0xfc,
	0x6f, 0x52, 0xea, 0xf5, 0xfc, 0xcd, 0xfb, 0x6f, 0xa7, 0x91, 0x8a, 0xe9, 0xa4, 0xc7, 0xef, 0x15,
	0xfd, 0x46, 0xf2, 0x78, 0xae, 0xd7, 0x8e, 0xec, 0x05, 0x7c, 0x76, 0x9a, 0x39, 0x38, 0x9d, 0xd0,
	0xe0, 0x1e, 0x59, 0x78, 0x9a, 0x3a, 0x9a, 0xec, 0x98, 0x3f, 0x98, 0x6f, 0xfe, 0x0d, 0x00, 0x00,
	0xff, 0xff, 0xb6, 0x11, 0xfb, 0xf7, 0x6d, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ZooplaServiceClient is the client API for ZooplaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ZooplaServiceClient interface {
	BranchUpdate(ctx context.Context, in *BranchUpdateRequest, opts ...grpc.CallOption) (*BranchUpdateResponse, error)
	UpdateProperty(ctx context.Context, in *ListingUpdateRequest, opts ...grpc.CallOption) (*ListingUpdateResponse, error)
	DeleteProperty(ctx context.Context, in *ListingDeleteRequest, opts ...grpc.CallOption) (*ListingDeleteResponse, error)
	Listing(ctx context.Context, in *ListingListRequest, opts ...grpc.CallOption) (*ListingListResponse, error)
}

type zooplaServiceClient struct {
	cc *grpc.ClientConn
}

func NewZooplaServiceClient(cc *grpc.ClientConn) ZooplaServiceClient {
	return &zooplaServiceClient{cc}
}

func (c *zooplaServiceClient) BranchUpdate(ctx context.Context, in *BranchUpdateRequest, opts ...grpc.CallOption) (*BranchUpdateResponse, error) {
	out := new(BranchUpdateResponse)
	err := c.cc.Invoke(ctx, "/mashroom.zoopla.ZooplaService/BranchUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zooplaServiceClient) UpdateProperty(ctx context.Context, in *ListingUpdateRequest, opts ...grpc.CallOption) (*ListingUpdateResponse, error) {
	out := new(ListingUpdateResponse)
	err := c.cc.Invoke(ctx, "/mashroom.zoopla.ZooplaService/UpdateProperty", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zooplaServiceClient) DeleteProperty(ctx context.Context, in *ListingDeleteRequest, opts ...grpc.CallOption) (*ListingDeleteResponse, error) {
	out := new(ListingDeleteResponse)
	err := c.cc.Invoke(ctx, "/mashroom.zoopla.ZooplaService/DeleteProperty", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zooplaServiceClient) Listing(ctx context.Context, in *ListingListRequest, opts ...grpc.CallOption) (*ListingListResponse, error) {
	out := new(ListingListResponse)
	err := c.cc.Invoke(ctx, "/mashroom.zoopla.ZooplaService/Listing", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ZooplaServiceServer is the server API for ZooplaService service.
type ZooplaServiceServer interface {
	BranchUpdate(context.Context, *BranchUpdateRequest) (*BranchUpdateResponse, error)
	UpdateProperty(context.Context, *ListingUpdateRequest) (*ListingUpdateResponse, error)
	DeleteProperty(context.Context, *ListingDeleteRequest) (*ListingDeleteResponse, error)
	Listing(context.Context, *ListingListRequest) (*ListingListResponse, error)
}

func RegisterZooplaServiceServer(s *grpc.Server, srv ZooplaServiceServer) {
	s.RegisterService(&_ZooplaService_serviceDesc, srv)
}

func _ZooplaService_BranchUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BranchUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZooplaServiceServer).BranchUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mashroom.zoopla.ZooplaService/BranchUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZooplaServiceServer).BranchUpdate(ctx, req.(*BranchUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZooplaService_UpdateProperty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListingUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZooplaServiceServer).UpdateProperty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mashroom.zoopla.ZooplaService/UpdateProperty",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZooplaServiceServer).UpdateProperty(ctx, req.(*ListingUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZooplaService_DeleteProperty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListingDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZooplaServiceServer).DeleteProperty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mashroom.zoopla.ZooplaService/DeleteProperty",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZooplaServiceServer).DeleteProperty(ctx, req.(*ListingDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZooplaService_Listing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListingListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZooplaServiceServer).Listing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mashroom.zoopla.ZooplaService/Listing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZooplaServiceServer).Listing(ctx, req.(*ListingListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ZooplaService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mashroom.zoopla.ZooplaService",
	HandlerType: (*ZooplaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BranchUpdate",
			Handler:    _ZooplaService_BranchUpdate_Handler,
		},
		{
			MethodName: "UpdateProperty",
			Handler:    _ZooplaService_UpdateProperty_Handler,
		},
		{
			MethodName: "DeleteProperty",
			Handler:    _ZooplaService_DeleteProperty_Handler,
		},
		{
			MethodName: "Listing",
			Handler:    _ZooplaService_Listing_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
