version: '3.5'
services:
  mashroom-zoopla:
    build:
      context: .
    image: "registry.gitlab.okta-solutions.com/mashroom/backend/zoopla:1.0.0"
    depends_on:
    - mongodb
    environment:
      ADDR: ":10000"
      MONGO_URL: "mongodb:27017"
      MONGO_DATABASE: "zoopla-data"
      MONGO_USERNAME: "zoopla-data"
      MONGO_PASSWORD: "zoopla-data"
      ELASTIC_URL: ""
    expose:
    - 10000
    networks:
      mashroom:
        ipv4_address: "10.251.0.10"
    volumes:
    - "mashroom-zoopla:/data"
  mongodb:
    image: "registry.gitlab.okta-solutions.com/mashroom/backend/common/mongo:1.0"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "zoopla-data"
      MONGO_INITDB_ROOT_PASSWORD: "zoopla-data"
      MONGO_INITDB_DATABASE: "zoopla-data"
    expose:
    - 27017
    networks:
      mashroom:
        ipv4_address: "10.251.0.11"
    volumes:
    - "mashroom-zoopla-mongo:/data/db"
networks:
  mashroom:
    name: mashroom
    driver: bridge
    ipam:
      config:
      - subnet: "10.251.0.0/24"
volumes:
  mashroom-zoopla:
  mashroom-zoopla-mongo: